typedef struct
{
	char pad0[8];
	char* displayName; // type: 0
	char pad1[8];
	float adsZoomFov; // type: 7
	int adsTransInTime; // type: 9
	int adsTransOutTime; // type: 9
	int clipSize; // type: 4
	int impactType; // type: 20
	int fireTime; // type: 9
	int dpadIconRatio; // type: 37
	float penetrateMultiplier; // type: 7
	float adsViewKickCenterSpeed; // type: 7
	float hipViewKickCenterSpeed; // type: 7
	char* altWeapon; // type: 0
	char pad2[4];
	int altRaiseTime; // type: 9
	int killIcon; // type: 12
	int dpadIcon; // type: 12
	char pad3[4];
	int firstRaiseTime; // type: 9
	int dropAmmoMax; // type: 4
	float adsDofStart; // type: 7
	float adsDofEnd; // type: 7
	char pad4[12];
	bool motionTracker; // type: 6
	bool enhanced; // type: 6
	bool dpadIconShowsAmmo; // type: 6
	char pad5[1];
	char* AIOverlayDescription; // type: 0
	char pad6[4];
	int handModel; // type: 11
	char pad7[8];
	char* modeName; // type: 0
	char pad8[16];
	int playerAnimType; // type: 24
	int weaponType; // type: 16
	int weaponClass; // type: 17
	int penetrateType; // type: 19
	int inventoryType; // type: 30
	int fireType; // type: 31
	int offhandClass; // type: 23
	int stance; // type: 21
	void* viewFlashEffect; // type: 10
	void* worldFlashEffect; // type: 10
	void* pickupSound; // type: 14
	void* pickupSoundPlayer; // type: 14
	void* ammoPickupSound; // type: 14
	void* ammoPickupSoundPlayer; // type: 14
	void* projectileSound; // type: 14
	void* pullbackSound; // type: 14
	void* pullbackSoundPlayer; // type: 14
	void* fireSound; // type: 14
	void* fireSoundPlayer; // type: 14
	void* fireSoundPlayerAkimbo; // type: 14
	void* loopFireSound; // type: 14
	void* loopFireSoundPlayer; // type: 14
	void* stopFireSound; // type: 14
	void* stopFireSoundPlayer; // type: 14
	void* lastShotSound; // type: 14
	void* lastShotSoundPlayer; // type: 14
	void* emptyFireSound; // type: 14
	void* emptyFireSoundPlayer; // type: 14
	void* meleeSwipeSound; // type: 14
	void* meleeSwipeSoundPlayer; // type: 14
	void* meleeHitSound; // type: 14
	void* meleeMissSound; // type: 14
	void* rechamberSound; // type: 14
	void* rechamberSoundPlayer; // type: 14
	void* reloadSound; // type: 14
	void* reloadSoundPlayer; // type: 14
	void* reloadEmptySound; // type: 14
	void* reloadEmptySoundPlayer; // type: 14
	void* reloadStartSound; // type: 14
	void* reloadStartSoundPlayer; // type: 14
	void* reloadEndSound; // type: 14
	void* reloadEndSoundPlayer; // type: 14
	void* detonateSound; // type: 14
	void* detonateSoundPlayer; // type: 14
	void* nightVisionWearSound; // type: 14
	void* nightVisionWearSoundPlayer; // type: 14
	void* nightVisionRemoveSound; // type: 14
	void* nightVisionRemoveSoundPlayer; // type: 14
	void* altSwitchSound; // type: 14
	void* altSwitchSoundPlayer; // type: 14
	void* raiseSound; // type: 14
	void* raiseSoundPlayer; // type: 14
	void* firstRaiseSound; // type: 14
	void* firstRaiseSoundPlayer; // type: 14
	void* putawaySound; // type: 14
	void* putawaySoundPlayer; // type: 14
	void* scanSound; // type: 14
	int bounceSound; // type: 27
	void* viewShellEjectEffect; // type: 10
	void* worldShellEjectEffect; // type: 10
	void* viewLastShotEjectEffect; // type: 10
	void* worldLastShotEjectEffect; // type: 10
	int reticleCenter; // type: 12
	int reticleSide; // type: 12
	int reticleCenterSize; // type: 4
	int reticleSideSize; // type: 4
	int reticleMinOfs; // type: 4
	int activeReticleType; // type: 25
	float standMoveF; // type: 7
	float standMoveR; // type: 7
	float standMoveU; // type: 7
	float standRotP; // type: 7
	float standRotY; // type: 7
	float standRotR; // type: 7
	float strafeMoveF; // type: 7
	float strafeMoveR; // type: 7
	float strafeMoveU; // type: 7
	float strafeRotP; // type: 7
	float strafeRotY; // type: 7
	float strafeRotR; // type: 7
	float duckedOfsF; // type: 7
	float duckedOfsR; // type: 7
	float duckedOfsU; // type: 7
	float duckedMoveF; // type: 7
	float duckedMoveR; // type: 7
	float duckedMoveU; // type: 7
	float duckedRotP; // type: 7
	float duckedRotY; // type: 7
	float duckedRotR; // type: 7
	float proneOfsF; // type: 7
	float proneOfsR; // type: 7
	float proneOfsU; // type: 7
	float proneMoveF; // type: 7
	float proneMoveR; // type: 7
	float proneMoveU; // type: 7
	float proneRotP; // type: 7
	float proneRotY; // type: 7
	float proneRotR; // type: 7
	float posMoveRate; // type: 7
	float posProneMoveRate; // type: 7
	float standMoveMinSpeed; // type: 7
	float duckedMoveMinSpeed; // type: 7
	float proneMoveMinSpeed; // type: 7
	float posRotRate; // type: 7
	float posProneRotRate; // type: 7
	float standRotMinSpeed; // type: 7
	float duckedRotMinSpeed; // type: 7
	float proneRotMinSpeed; // type: 7
	char pad9[4];
	int worldClipModel; // type: 11
	int rocketModel; // type: 11
	int knifeModel; // type: 11
	int worldKnifeModel; // type: 11
	int hudIcon; // type: 12
	int hudIconRatio; // type: 33
	int pickupIcon; // type: 12
	int pickupIconRatio; // type: 34
	int ammoCounterIcon; // type: 12
	int ammoCounterIconRatio; // type: 35
	int ammoCounterClip; // type: 32
	int startAmmo; // type: 4
	char* ammoName; // type: 0
	char pad10[4];
	char* clipName; // type: 0
	char pad11[4];
	int maxAmmo; // type: 4
	int shotCount; // type: 4
	char* sharedAmmoCapName; // type: 0
	char pad12[4];
	int sharedAmmoCap; // type: 4
	int damage; // type: 4
	int playerDamage; // type: 4
	int meleeDamage; // type: 4
	char pad13[4];
	int fireDelay; // type: 9
	int meleeDelay; // type: 9
	int meleeChargeDelay; // type: 9
	int detonateDelay; // type: 9
	int rechamberTime; // type: 9
	int rechamberTimeOneHanded; // type: 9
	int rechamberBoltTime; // type: 9
	int holdFireTime; // type: 9
	int detonateTime; // type: 9
	int meleeTime; // type: 9
	int meleeChargeTime; // type: 9
	int reloadTime; // type: 9
	int reloadShowRocketTime; // type: 9
	int reloadEmptyTime; // type: 9
	int reloadAddTime; // type: 9
	int reloadStartTime; // type: 9
	int reloadStartAddTime; // type: 9
	int reloadEndTime; // type: 9
	int dropTime; // type: 9
	int raiseTime; // type: 9
	int altDropTime; // type: 9
	int quickDropTime; // type: 9
	int quickRaiseTime; // type: 9
	int breachRaiseTime; // type: 9
	int emptyRaiseTime; // type: 9
	int emptyDropTime; // type: 9
	int sprintInTime; // type: 9
	int sprintLoopTime; // type: 9
	int sprintOutTime; // type: 9
	int stunnedTimeBegin; // type: 9
	int stunnedTimeLoop; // type: 9
	int stunnedTimeEnd; // type: 9
	int nightVisionWearTime; // type: 9
	int nightVisionWearTimeFadeOutEnd; // type: 9
	int nightVisionWearTimePowerUp; // type: 9
	int nightVisionRemoveTime; // type: 9
	int nightVisionRemoveTimePowerDown; // type: 9
	int nightVisionRemoveTimeFadeInStart; // type: 9
	int fuseTime; // type: 9
	int aifuseTime; // type: 9
	float autoAimRange; // type: 7
	float aimAssistRange; // type: 7
	float aimAssistRangeAds; // type: 7
	float aimPadding; // type: 7
	float enemyCrosshairRange; // type: 7
	float moveSpeedScale; // type: 7
	float adsMoveSpeedScale; // type: 7
	float sprintDurationScale; // type: 7
	float adsZoomInFrac; // type: 7
	float adsZoomOutFrac; // type: 7
	int adsOverlayShader; // type: 12
	int adsOverlayShaderLowRes; // type: 12
	int adsOverlayShaderEMP; // type: 12
	int adsOverlayShaderEMPLowRes; // type: 12
	int adsOverlayReticle; // type: 18
	int adsOverlayInterface; // type: 29
	float adsOverlayWidth; // type: 7
	float adsOverlayHeight; // type: 7
	float adsOverlayWidthSplitscreen; // type: 7
	float adsOverlayHeightSplitscreen; // type: 7
	float adsBobFactor; // type: 7
	float adsViewBobMult; // type: 7
	float hipSpreadStandMin; // type: 7
	float hipSpreadDuckedMin; // type: 7
	float hipSpreadProneMin; // type: 7
	float hipSpreadMax; // type: 7
	float hipSpreadDuckedMax; // type: 7
	float hipSpreadProneMax; // type: 7
	float hipSpreadDecayRate; // type: 7
	float hipSpreadFireAdd; // type: 7
	float hipSpreadTurnAdd; // type: 7
	float hipSpreadMoveAdd; // type: 7
	float hipSpreadDuckedDecay; // type: 7
	float hipSpreadProneDecay; // type: 7
	float hipReticleSidePos; // type: 7
	float adsIdleAmount; // type: 7
	float hipIdleAmount; // type: 7
	float adsIdleSpeed; // type: 7
	float hipIdleSpeed; // type: 7
	float idleCrouchFactor; // type: 7
	float idleProneFactor; // type: 7
	float gunMaxPitch; // type: 7
	float gunMaxYaw; // type: 7
	float swayMaxAngle; // type: 7
	float swayLerpSpeed; // type: 7
	float swayPitchScale; // type: 7
	float swayYawScale; // type: 7
	float swayHorizScale; // type: 7
	float swayVertScale; // type: 7
	float swayShellShockScale; // type: 7
	float adsSwayMaxAngle; // type: 7
	float adsSwayLerpSpeed; // type: 7
	float adsSwayPitchScale; // type: 7
	float adsSwayYawScale; // type: 7
	float adsSwayHorizScale; // type: 7
	float adsSwayVertScale; // type: 7
	float adsViewErrorMin; // type: 7
	float adsViewErrorMax; // type: 7
	void* physCollmap; // type: 13
	float dualWieldViewModelOffset; // type: 7
	int killIconRatio; // type: 36
	int reloadAmmoAdd; // type: 4
	int reloadStartAdd; // type: 4
	int dropAmmoMin; // type: 4
	int ammoDropClipPercentMin; // type: 4
	int ammoDropClipPercentMax; // type: 4
	int explosionRadius; // type: 4
	int explosionRadiusMin; // type: 4
	int explosionInnerDamage; // type: 4
	int explosionOuterDamage; // type: 4
	float damageConeAngle; // type: 7
	float bulletExplDmgMult; // type: 7
	float bulletExplRadiusMult; // type: 7
	int projectileSpeed; // type: 4
	int projectileSpeedUp; // type: 4
	int projectileSpeedForward; // type: 4
	int projectileActivateDist; // type: 4
	float projectileLifetime; // type: 7
	float timeToAccelerate; // type: 7
	float projectileCurvature; // type: 7
	int projectileModel; // type: 11
	int projExplosionType; // type: 22
	void* projExplosionEffect; // type: 10
	void* projDudEffect; // type: 10
	void* projExplosionSound; // type: 14
	void* projDudSound; // type: 14
	int stickiness; // type: 28
	float lowAmmoWarningThreshold; // type: 7
	float ricochetChance; // type: 7
	char pad14[8];
	void* projTrailEffect; // type: 10
	void* projBeaconEffect; // type: 10
	float projectileRed; // type: 7
	float projectileGreen; // type: 7
	float projectileBlue; // type: 7
	int guidedMissileType; // type: 26
	float maxSteeringAccel; // type: 7
	int projIgnitionDelay; // type: 4
	void* projIgnitionEffect; // type: 10
	void* projIgnitionSound; // type: 14
	float adsAimPitch; // type: 7
	float adsCrosshairInFrac; // type: 7
	float adsCrosshairOutFrac; // type: 7
	int adsGunKickReducedKickBullets; // type: 4
	float adsGunKickReducedKickPercent; // type: 7
	float adsGunKickPitchMin; // type: 7
	float adsGunKickPitchMax; // type: 7
	float adsGunKickYawMin; // type: 7
	float adsGunKickYawMax; // type: 7
	float adsGunKickAccel; // type: 7
	float adsGunKickSpeedMax; // type: 7
	float adsGunKickSpeedDecay; // type: 7
	float adsGunKickStaticDecay; // type: 7
	float adsViewKickPitchMin; // type: 7
	float adsViewKickPitchMax; // type: 7
	float adsViewKickYawMin; // type: 7
	float adsViewKickYawMax; // type: 7
	char pad16[8];
	float adsSpread; // type: 7
	int hipGunKickReducedKickBullets; // type: 4
	float hipGunKickReducedKickPercent; // type: 7
	float hipGunKickPitchMin; // type: 7
	float hipGunKickPitchMax; // type: 7
	float hipGunKickYawMin; // type: 7
	float hipGunKickYawMax; // type: 7
	float hipGunKickAccel; // type: 7
	float hipGunKickSpeedMax; // type: 7
	float hipGunKickSpeedDecay; // type: 7
	float hipGunKickStaticDecay; // type: 7
	float hipViewKickPitchMin; // type: 7
	float hipViewKickPitchMax; // type: 7
	float hipViewKickYawMin; // type: 7
	float hipViewKickYawMax; // type: 7
	char pad17[8];
	float fightDist; // type: 7
	float maxDist; // type: 7
	char* aiVsAiAccuracyGraph; // type: 0
	char* aiVsPlayerAccuracyGraph; // type: 0
	char pad18[12];
	int adsReloadTransTime; // type: 9
	float leftArc; // type: 7
	float rightArc; // type: 7
	float topArc; // type: 7
	float bottomArc; // type: 7
	float accuracy; // type: 7
	float aiSpread; // type: 7
	float playerSpread; // type: 7
	float minVertTurnSpeed; // type: 7
	float minHorTurnSpeed; // type: 7
	float maxVertTurnSpeed; // type: 7
	float maxHorTurnSpeed; // type: 7
	float pitchConvergenceTime; // type: 7
	float yawConvergenceTime; // type: 7
	float suppressionTime; // type: 7
	float maxRange; // type: 7
	float animHorRotateInc; // type: 7
	float playerPositionDist; // type: 7
	char* useHintString; // type: 0
	char* dropHintString; // type: 0
	char pad19[8];
	float horizViewJitter; // type: 7
	float vertViewJitter; // type: 7
	float scanSpeed; // type: 7
	float scanAccel; // type: 7
	int scanPauseTime; // type: 9
	char* script; // type: 0
	char pad20[8];
	int minDamage; // type: 4
	int minPlayerDamage; // type: 4
	float maxDamageRange; // type: 7
	float minDamageRange; // type: 7
	float destabilizationRateTime; // type: 7
	float destabilizationCurvatureMax; // type: 7
	int destabilizeDistance; // type: 4
	char pad21[4];
	char* fireRumble; // type: 0
	char* meleeImpactRumble; // type: 0
	void* tracerType; // type: 15
	float turretScopeZoomRate; // type: 7
	float turretScopeZoomMin; // type: 7
	float turretScopeZoomMax; // type: 7
	float turretOverheatUpRate; // type: 7
	float turretOverheatDownRate; // type: 7
	float turretOverheatPenalty; // type: 7
	void* turretOverheatSound; // type: 14
	void* turretOverheatEffect; // type: 10
	char* turretBarrelSpinRumble; // type: 0
	float turretBarrelSpinSpeed; // type: 7
	float turretBarrelSpinUpTime; // type: 7
	float turretBarrelSpinDownTime; // type: 7
	void* turretBarrelSpinMaxSnd; // type: 14
	void* turretBarrelSpinUpSnd1; // type: 14
	void* turretBarrelSpinUpSnd2; // type: 14
	void* turretBarrelSpinUpSnd3; // type: 14
	void* turretBarrelSpinUpSnd4; // type: 14
	void* turretBarrelSpinDownSnd1; // type: 14
	void* turretBarrelSpinDownSnd2; // type: 14
	void* turretBarrelSpinDownSnd3; // type: 14
	void* turretBarrelSpinDownSnd4; // type: 14
	void* missileConeSoundAlias; // type: 14
	void* missileConeSoundAliasAtBase; // type: 14
	float missileConeSoundRadiusAtTop; // type: 7
	float missileConeSoundRadiusAtBase; // type: 7
	float missileConeSoundHeight; // type: 7
	float missileConeSoundOriginOffset; // type: 7
	float missileConeSoundVolumescaleAtCore; // type: 7
	float missileConeSoundVolumescaleAtEdge; // type: 7
	float missileConeSoundVolumescaleCoreSize; // type: 7
	float missileConeSoundPitchAtTop; // type: 7
	float missileConeSoundPitchAtBottom; // type: 7
	float missileConeSoundPitchTopSize; // type: 7
	float missileConeSoundPitchBottomSize; // type: 7
	float missileConeSoundCrossfadeTopSize; // type: 7
	float missileConeSoundCrossfadeBottomSize; // type: 7
	bool shareAmmo; // type: 6
	bool lockonSupported; // type: 6
	bool requireLockonToFire; // type: 6
	bool bigExplosion; // type: 6
	bool noAdsWhenMagEmpty; // type: 6
	bool avoidDropCleanup; // type: 6
	bool inheritsPerks; // type: 6
	bool crosshairColorChange; // type: 6
	bool rifleBullet; // type: 6
	bool armorPiercing; // type: 6
	bool boltAction; // type: 6
	bool aimDownSight; // type: 6
	bool rechamberWhileAds; // type: 6
	bool bBulletExplosiveDamage; // type: 6
	bool cookOffHold; // type: 6
	bool clipOnly; // type: 6
	bool noAmmoPickup; // type: 6
	bool adsFire; // type: 6
	bool cancelAutoHolsterWhenEmpty; // type: 6
	bool disableSwitchToWhenEmpty; // type: 6
	bool suppressAmmoReserveDisplay; // type: 6
	bool laserSightDuringNightvision; // type: 6
	bool markableViewmodel; // type: 6
	bool noDualWield; // type: 6
	bool flipKillIcon; // type: 6
	bool noPartialReload; // type: 6
	bool segmentedReload; // type: 6
	bool blocksProne; // type: 6
	bool silenced; // type: 6
	bool isRollingGrenade; // type: 6
	bool projExplosionEffectForceNormalUp; // type: 6
	bool projImpactExplode; // type: 6
	bool stickToPlayers; // type: 6
	bool hasDetonator; // type: 6
	bool disableFiring; // type: 6
	bool timedDetonation; // type: 6
	bool rotate; // type: 6
	bool holdButtonToThrow; // type: 6
	bool freezeMovementWhenFiring; // type: 6
	bool thermalScope; // type: 6
	bool altModeSameWeapon; // type: 6
	bool turretBarrelSpinEnabled; // type: 6
	bool missileConeSoundEnabled; // type: 6
	bool missileConeSoundPitchshiftEnabled; // type: 6
	bool missileConeSoundCrossfadeEnabled; // type: 6
	bool offhandHoldIsCancelable; // type: 6
	char pad22[2];
	void* hideTags; // type: 38
	char pad23[64];
	char* idleAnim; // type: 0
	char* emptyIdleAnim; // type: 0
	char* fireAnim; // type: 0
	char* holdFireAnim; // type: 0
	char* lastShotAnim; // type: 0
	char* rechamberAnim; // type: 0
	char* meleeAnim; // type: 0
	char* meleeChargeAnim; // type: 0
	char* reloadAnim; // type: 0
	char* reloadEmptyAnim; // type: 0
	char* reloadStartAnim; // type: 0
	char* reloadEndAnim; // type: 0
	char* raiseAnim; // type: 0
	char* firstRaiseAnim; // type: 0
	char* breachRaiseAnim; // type: 0
	char* dropAnim; // type: 0
	char* altRaiseAnim; // type: 0
	char* altDropAnim; // type: 0
	char* quickRaiseAnim; // type: 0
	char* quickDropAnim; // type: 0
	char* emptyRaiseAnim; // type: 0
	char* emptyDropAnim; // type: 0
	char* sprintInAnim; // type: 0
	char* sprintLoopAnim; // type: 0
	char* sprintOutAnim; // type: 0
	char* stunnedAnimStart; // type: 0
	char* stunnedAnimLoop; // type: 0
	char* stunnedAnimEnd; // type: 0
	char* detonateAnim; // type: 0
	char* nightVisionWearAnim; // type: 0
	char* nightVisionRemoveAnim; // type: 0
	char* adsFireAnim; // type: 0
	char* adsLastShotAnim; // type: 0
	char* adsRechamberAnim; // type: 0
	char* adsUpAnim; // type: 0
	char* adsDownAnim; // type: 0
	int gunModel; // type: 11
	int gunModel2; // type: 11
	int gunModel3; // type: 11
	int gunModel4; // type: 11
	int gunModel5; // type: 11
	int gunModel6; // type: 11
	int gunModel7; // type: 11
	int gunModel8; // type: 11
	int gunModel9; // type: 11
	int gunModel10; // type: 11
	int gunModel11; // type: 11
	int gunModel12; // type: 11
	int gunModel13; // type: 11
	int gunModel14; // type: 11
	int gunModel15; // type: 11
	int gunModel16; // type: 11
	char pad24[4];
	char* idleAnimR; // type: 0
	char* emptyIdleAnimR; // type: 0
	char* fireAnimR; // type: 0
	char* holdFireAnimR; // type: 0
	char* lastShotAnimR; // type: 0
	char* rechamberAnimR; // type: 0
	char* meleeAnimR; // type: 0
	char* meleeChargeAnimR; // type: 0
	char* reloadAnimR; // type: 0
	char* reloadEmptyAnimR; // type: 0
	char* reloadStartAnimR; // type: 0
	char* reloadEndAnimR; // type: 0
	char* raiseAnimR; // type: 0
	char* firstRaiseAnimR; // type: 0
	char* breachRaiseAnimR; // type: 0
	char* dropAnimR; // type: 0
	char* altRaiseAnimR; // type: 0
	char* altDropAnimR; // type: 0
	char* quickRaiseAnimR; // type: 0
	char* quickDropAnimR; // type: 0
	char* emptyRaiseAnimR; // type: 0
	char* emptyDropAnimR; // type: 0
	char* sprintInAnimR; // type: 0
	char* sprintLoopAnimR; // type: 0
	char* sprintOutAnimR; // type: 0
	char* stunnedAnimStartR; // type: 0
	char* stunnedAnimLoopR; // type: 0
	char* stunnedAnimEndR; // type: 0
	char* detonateAnimR; // type: 0
	char* nightVisionWearAnimR; // type: 0
	char* nightVisionRemoveAnimR; // type: 0
	char* adsFireAnimR; // type: 0
	char* adsLastShotAnimR; // type: 0
	char* adsRechamberAnimR; // type: 0
	char* adsUpAnimR; // type: 0
	char* adsDownAnimR; // type: 0
	char pad25[4];
	char* idleAnimL; // type: 0
	char* emptyIdleAnimL; // type: 0
	char* fireAnimL; // type: 0
	char* holdFireAnimL; // type: 0
	char* lastShotAnimL; // type: 0
	char* rechamberAnimL; // type: 0
	char* meleeAnimL; // type: 0
	char* meleeChargeAnimL; // type: 0
	char* reloadAnimL; // type: 0
	char* reloadEmptyAnimL; // type: 0
	char* reloadStartAnimL; // type: 0
	char* reloadEndAnimL; // type: 0
	char* raiseAnimL; // type: 0
	char* firstRaiseAnimL; // type: 0
	char* breachRaiseAnimL; // type: 0
	char* dropAnimL; // type: 0
	char* altRaiseAnimL; // type: 0
	char* altDropAnimL; // type: 0
	char* quickRaiseAnimL; // type: 0
	char* quickDropAnimL; // type: 0
	char* emptyRaiseAnimL; // type: 0
	char* emptyDropAnimL; // type: 0
	char* sprintInAnimL; // type: 0
	char* sprintLoopAnimL; // type: 0
	char* sprintOutAnimL; // type: 0
	char* stunnedAnimStartL; // type: 0
	char* stunnedAnimLoopL; // type: 0
	char* stunnedAnimEndL; // type: 0
	char* detonateAnimL; // type: 0
	char* nightVisionWearAnimL; // type: 0
	char* nightVisionRemoveAnimL; // type: 0
	char* adsFireAnimL; // type: 0
	char* adsLastShotAnimL; // type: 0
	char* adsRechamberAnimL; // type: 0
	char* adsUpAnimL; // type: 0
	char* adsDownAnimL; // type: 0
	void* notetrackSoundMap; // type: 39
	char pad26[60];
	void* notetrackRumbleMap; // type: 40
	char pad27[60];
	int worldModel; // type: 11
	int worldModel2; // type: 11
	int worldModel3; // type: 11
	int worldModel4; // type: 11
	int worldModel5; // type: 11
	int worldModel6; // type: 11
	int worldModel7; // type: 11
	int worldModel8; // type: 11
	int worldModel9; // type: 11
	int worldModel10; // type: 11
	int worldModel11; // type: 11
	int worldModel12; // type: 11
	int worldModel13; // type: 11
	int worldModel14; // type: 11
	int worldModel15; // type: 11
	int worldModel16; // type: 11
	float parallelDefaultBounce; // type: 7
	float parallelBarkBounce; // type: 7
	float parallelBrickBounce; // type: 7
	float parallelCarpetBounce; // type: 7
	float parallelClothBounce; // type: 7
	float parallelConcreteBounce; // type: 7
	float parallelDirtBounce; // type: 7
	float parallelFleshBounce; // type: 7
	float parallelFoliageBounce; // type: 7
	float parallelGlassBounce; // type: 7
	float parallelGrassBounce; // type: 7
	float parallelGravelBounce; // type: 7
	float parallelIceBounce; // type: 7
	float parallelMetalBounce; // type: 7
	float parallelMudBounce; // type: 7
	float parallelPaperBounce; // type: 7
	float parallelPlasterBounce; // type: 7
	float parallelRockBounce; // type: 7
	float parallelSandBounce; // type: 7
	float parallelSnowBounce; // type: 7
	float parallelWaterBounce; // type: 7
	float parallelWoodBounce; // type: 7
	float parallelAsphaltBounce; // type: 7
	float CeramicBounce; // type: 7
	float PlasticBounce; // type: 7
	float RubberBounce; // type: 7
	float parallelCushionBounce; // type: 7
	float parallelFruitBounce; // type: 7
	float parallelPaintedMetalBounce; // type: 7
	float parallelRiotShieldBounce; // type: 7
	float parallelSlushBounce; // type: 7
	float perpendicularDefaultBounce; // type: 7
	float perpendicularBarkBounce; // type: 7
	float perpendicularBrickBounce; // type: 7
	float perpendicularCarpetBounce; // type: 7
	float perpendicularClothBounce; // type: 7
	float perpendicularConcreteBounce; // type: 7
	float perpendicularDirtBounce; // type: 7
	float perpendicularFleshBounce; // type: 7
	float perpendicularFoliageBounce; // type: 7
	float perpendicularGlassBounce; // type: 7
	float perpendicularGrassBounce; // type: 7
	float perpendicularGravelBounce; // type: 7
	float perpendicularIceBounce; // type: 7
	float perpendicularMetalBounce; // type: 7
	float perpendicularMudBounce; // type: 7
	float perpendicularPaperBounce; // type: 7
	float perpendicularPlasterBounce; // type: 7
	float perpendicularRockBounce; // type: 7
	float perpendicularSandBounce; // type: 7
	float perpendicularSnowBounce; // type: 7
	float perpendicularWaterBounce; // type: 7
	float perpendicularWoodBounce; // type: 7
	float perpendicularAsphaltBounce; // type: 7
	char pad31[12];
	float perpendicularCushionBounce; // type: 7
	float perpendicularFruitBounce; // type: 7
	float perpendicularPaintedMetalBounce; // type: 7
	float perpendicularRiotShieldBounce; // type: 7
	float perpendicularSlushBounce; // type: 7
	float locNone; // type: 7
	float locHelmet; // type: 7
	float locHead; // type: 7
	float locNeck; // type: 7
	float locTorsoUpper; // type: 7
	float locTorsoLower; // type: 7
	float locRightArmUpper; // type: 7
	float locLeftArmUpper; // type: 7
	float locRightArmLower; // type: 7
	float locLeftArmLower; // type: 7
	float locRightHand; // type: 7
	float locLeftHand; // type: 7
	float locRightLegUpper; // type: 7
	float locLeftLegUpper; // type: 7
	float locRightLegLower; // type: 7
	float locLeftLegLower; // type: 7
	float locRightFoot; // type: 7
	float locLeftFoot; // type: 7
	float locGun; // type: 7
} WeaponDef_t;
